### ISSUE TITLE
Upcoming feature with league 

### ISSUE THREAD

**Issue by flo-h-rian** [architv/soccer-cli#109]
First of all. Great project, I really like it.

I do not know whether this is an issue or a feature request. I did not manage to get the upcoming feature to work with a league and not just a specific team.

```
soccer --league=BL --time=7 --upcoming
No BL matches in the past week.
```

In the help it says "Displays upcoming games when used with --time command.", but a potential restriction to a specific team is not mentioned.

Best,
Florian

**Comment by dfrt82** [comment]
I think `soccer --team=PSG --time=7 --upcoming` does what you want to?!

**Comment by flo-h-rian** [comment]
Yes, soccer --team=XY --upcoming does show me the upcoming events for team XY. What I would appreciate to have is to see all upcoming games for a certain league, not just a single team. E.g. print all premier league games in the next 7 days. Sorry, If this did not become clear previously.

**Comment by villadalmine** [comment]
HI, Sorry maybe I did not explain it..
I want to know if I can add the Argentinian football or if it is in your plan because the api that you use in the source code did not support South American matches.
---
Rondan Rino
Certificado en LPIC-2  <https://cs.lpi.org/caf/Xamman/certification>
LPI ID:LPI000209832
Verification Code:gbblvwyfxu
Red Hat Certified Engineer -- RHCE -- RHCVA <https://www.redhat.com/rhtapps/certification/verify/?certId=120-175-658> 


Blog:http://www.itrestauracion.com.ar <http://www.itrestauracion.com.ar/>
Cv: http://cv.rinorondan.com.ar <http://www.rinorondan.com.ar/>
http://counter.li.org <http://counter.li.org/>  Linux User -> #517918
Viva La Santa Federacion!!
Mueran Los Salvages Unitarios!! 
^^^Transcripcion de la epoca ^^^

**Comment by dfrt82** [comment]
Well :-) Then the upper command is what you want to go with. When you fired the command, apparently there were no games in the next 7 days and the error message is misleading (should say 'specified date range' or something). 
Currently next games in most leagues start in about two weeks because of the international games, so be sure to take --time=20 or the like.

**Comment by flo-h-rian** [comment]
I think this is not the problem. When I first tried it with "Bundesliga" there were games scheduled for the next weekend. Now, the next Bundesliga-match is on March 31st, so in 10 days. 
Still calling with time=20 or event time=100 does not print these:

soccer --league=BL --time=100 --upcoming
No BL matches in the past week.

**Comment by dfrt82** [comment]
Sorry, cannot reproduce. Working perfectly here, so it's an issue with your instance.

`dfrt@raspberrypi:~ $ soccer --league=BL --time=12 --upcoming
============================= BL =============================

Hertha BSC                 -  vs  -       TSG 1899 Hoffenheim   Fri 31, 19:30
Red Bull Leipzig           -  vs  -           SV Darmstadt 98   Sat 01, 14:30
FC Schalke 04              -  vs  -         Borussia Dortmund   Sat 01, 14:30
Hamburger SV               -  vs  -                1. FC Köln   Sat 01, 14:30
SC Freiburg                -  vs  -             Werder Bremen   Sat 01, 14:30
FC Bayern München          -  vs  -               FC Augsburg   Sat 01, 14:30
Eintracht Frankfurt        -  vs  -      Bor. Mönchengladbach   Sat 01, 17:30
dfrt@raspberrypi:~ $`
