### ISSUE TITLE
not really an issue.... code stuff

### ISSUE THREAD

**Issue by suhussai** [architv/soccer-cli#27]
I was looking over the codebase and noticed a few things. 
Your indents were tabs instead of spaces.
Indents are 8 spaces (two indents) instead of 4 spaces(one indent)
Several lines in main.py, and possibly others, are longer than 80 characters

I was actually thinking of submitting a PR for the 80 characters thing, but couldn't due to the other points I mentioned. I don't know if this is what you wanted, but I just wanted to mention it.

**Comment by Saturn** [comment]
Yea it should really use spaces instead of tabs. I will maybe submit a PR that replaces the tabs with spaces and @architv can decide if he wants to do it.

Some lines are too long and there is some general formatting problems. If you could clean up some of the long lines in a good way it might be useful :smile:

**Comment by Saturn** [comment]
Some of the files use spaces instead of tabs too :unamused:

**Comment by architv** [comment]
Fixed.
